# @package _global_

# Default configuration for experiments
defaults:
  - model: mlp
  - dataset: cifar10
  - optimizer: adam
  - training: continual
  - metrics: default
  - _self_

# Logging defaults
logging:
  summary: true

# Execution mode
use_wandb: true
wandb_project: "continual-learning-experiment"
wandb_tags: []
dryrun: false

# Hydra-specific configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
