# @package _global_.metrics
metrics_frequency: 5
dead_threshold: 0.95
corr_threshold: 0.95
saturation_threshold: 1e-4
saturation_percentage: 0.99
gaussianity_method: "shapiro"  # Options: "shapiro", "ks", "anderson", "kurtosis"
log_activation_histograms: true
# List of string patterns to filter which layers to monitor
# If empty, all layers will be monitored
# Example: ["linear", ".mlp", "fc"] would only monitor linear, mlp, and fully connected layers
monitor_filters: []
