# @package _global_.metrics
metrics_frequency: 100

# Which metrics to compute (in list). If null → compute all available.
# Options: dead_fraction, dup_fraction, eff_rank, stable_rank, saturated_frac, non_gaussianity, mean_abs_off_diag_correlation
selected_metrics: [eff_rank, stable_rank, mean_abs_off_diag_correlation]

# Parameters for the metrics
dead_threshold: 0.95  # dead_fraction
corr_threshold: 0.95  # dup_fraction
saturation_threshold: 1e-4  # saturated_frac
saturation_percentage: 0.99   # saturated_frac
gaussianity_method: "shapiro"  # Options: "shapiro", "ks", "anderson", "kurtosis"

log_activation_histograms: True

# List of string patterns to filter which layers to monitor
# If empty, all layers will be monitored
# For cloning experiments, we need to monitor hidden layers
monitor_filters: ["default"]
