# @package _global_.model
name: resnet
_target_: src.models.ResNet

# ResNet parameters
layers: [2, 2, 2, 2]
base_channels: 64
activation: relu
dropout_p: 0.1
normalization: batch
norm_after_activation: false
normalization_affine: true