# @package _global_.model
name: vit
_target_: src.models.VisionTransformer

vit:
  patch_size: 8
  embed_dim: 384
  depth: 6
  n_heads: 6
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.1
  attn_drop_rate: 0.1
  activation: gelu
  normalization: layer
  normalization_affine: true
