# @package _global_.optimizer
name: rmsprop
lr: 0.0001
weight_decay: 0.0
alpha: 0.99  # Default RMSprop alpha (smoothing constant)
eps: 1e-8  # Default RMSprop epsilon
momentum: 0.0  # Default RMSprop momentum
centered: false  # Default RMSprop centered
reinit_optimizer: true  # Flag for reinitializing optimizer
