# @package _global_.training
# Base model training
training_type: "cloning"
initial_epochs: 5  # How many epochs to train the base model

# Expansion parameters
epochs_per_expansion: 20  # How many epochs to train each expanded model
expansion_factor: 2  # Factor to expand model size (e.g., 2 = double the size)
num_expansions: 1  # Number of expansions to perform (1 = just base + 1 expansion)

# General parameters
batch_size: 128
num_workers: 2
no_augment: false
early_stopping_steps: 0
seed: 42
device: null

# Retain base model parameters
track_base: true  # Whether to keep training the original model alongside the expanded models

# These are needed for compatibility with the data loading pipeline
tasks: null
classes_per_task: null  # Will use all classes
partitions: null
reset: false