# @package _global_.training

epochs_per_task: 20
batch_size: 128
no_augment: false
early_stopping_steps: 5
reinit_output: true
reset: false
seed: 42
device: null  # Will auto-select based on availability
