# @package _global_.training
training_type: "continual"
epochs_per_task: 20
batch_size: 128
num_workers: 2
no_augment: false
early_stopping_steps: 0
reset: false
seed: 42
device: null
compile: false

# Task configurations (merged from task section)
tasks: 5
classes_per_task: 2
partitions: null
