# @package _global_.training
training_type: "continual"
epochs_per_task: 10
batch_size: 128
fixed_batch_size: 2048
num_workers: 2
no_augment: false
early_stopping_steps: 0
reset: false
seed: 42
device: null
eigenval_reg_lambda: 0.0
eigenval_reg_momentum: 0.99

# Task configurations (merged from task section)
tasks: 5
classes_per_task: 2
partitions: null
