# @package _global_.training
training_type: "standard"
epochs_per_task: 10
batch_size: 128
fixed_batch_size: 2048
num_workers: 1
no_augment: false
early_stopping_steps: 0
reset: false
seed: 42
device: null
eigenval_reg_lambda: 0.0
eigenval_reg_momentum: 0.99

# Task configurations (merged from task section)
tasks: null
classes_per_task: null  # Will use all classes
partitions: null
